### ISSUE TITLE
some warning when make k2

### ISSUE THREAD

**Issue by cdxie** [k2-fsa/k2#818]
hi, when I make the k2，i get some warnings：
1、(just some of the one warnings)
  CMake Warning at k2/csrc/CMakeLists.txt:177 (add_executable):
  Cannot generate a safe runtime search path for target cu_array_test because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcufft.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libcurand.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libcublas.so.11] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libnvrtc.so.11.1] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libnvToolsExt.so.1] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libcudart.so.11.0] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  k2/csrc/CMakeLists.txt:201 (k2_add_cuda_test)

CMake Warning at k2/csrc/CMakeLists.txt:177 (add_executable):
  Cannot generate a safe runtime search path for target cu_ragged_test
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcufft.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libcurand.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libcublas.so.11] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libnvrtc.so.11.1] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libnvToolsExt.so.1] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libcudart.so.11.0] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  k2/csrc/CMakeLists.txt:201 (k2_add_cuda_test)

CMake Warning at k2/csrc/CMakeLists.txt:177 (add_executable):
  Cannot generate a safe runtime search path for target cu_nvtx_test because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcufft.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libcurand.so.10] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libcublas.so.11] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libnvrtc.so.11.1] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libnvToolsExt.so.1] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib
    runtime library [libcudart.so.11.0] in /usr/local/cuda/lib64 may be hidden by files in:
      /opt/conda/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  k2/csrc/CMakeLists.txt:201 (k2_add_cuda_test)

I want to know these warnings will influence the next use?

**Comment by cdxie** [comment]
And, I use the following install steps :
git clone https://github.com/k2-fsa/k2.git
cd k2
python3 setup.py install

**Comment by pkufool** [comment]
It seems that you have two versions of cudatoolkit, I once encountered the same problem, when I uninstall one of my cudatoolkit in my virtual env, the error disppeared.

**Comment by cdxie** [comment]
> It seems that you have two versions of cudatoolkit, I once encountered the same problem, when I uninstalled one of my cudatoolkit in my virtual env, the error disappeared.

thanks , I will check the used of versions of cudatoolkit 。I use the pytorch docker image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel to install K2。 Normally, the other  cudatoolkits will not be reintroduced

**Comment by pkufool** [comment]
```
runtime library [libcublas.so.11] in /usr/local/cuda/lib64 may be hidden by files in:
  /opt/conda/lib
```
From the logs, there may be one cudatoolkit in your conda environment, in my case, there was the problem about cudatoolkit, you can check that, the error log was the same with yours.

**Comment by cdxie** [comment]
> ```
> runtime library [libcublas.so.11] in /usr/local/cuda/lib64 may be hidden by files in:
>   /opt/conda/lib
> ```
> 
> From the logs, there may be one cudatoolkit in your conda environment, in my case, there was the problem about cudatoolkit, you can check that, the error log was the same with yours.

I remove some runtime library, make is ok. thanks very much.
but I get  another warning:
-- K2_COMPUTE_ARCH_FLAGS: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
-- Adding arch 35
-- Adding arch 50
-- Adding arch 60
-- Adding arch 61
-- Adding arch 70
-- Adding arch 75
-- K2_COMPUTE_ARCHS: 35;50;60;61;70;75
CMake Warning at CMakeLists.txt:204 (message):
  arch 62/72 are not supported for now

**Comment by csukuangfj** [comment]
You can just ignore that warning. 

By the way, could you tell us the type/name of your nvidia GPU card? Looks like CMake didn't detect the correct architecture of your GPU card and it compiles k2 to support all possible architectures, which can take lots of time to compile.

**Comment by cdxie** [comment]
> You can just ignore that warning.
> 
> By the way, could you tell us the type/name of your nvidia GPU card? Looks like CMake didn't detect the correct architecture of your GPU card and it compiles k2 to support all possible architectures, which can take lots of time to compile.

thanks, I use the pytorch docker image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel to build a  K2 dockerfile,the above warning occurs during building

**Comment by pkufool** [comment]
> > You can just ignore that warning.
> > By the way, could you tell us the type/name of your nvidia GPU card? Looks like CMake didn't detect the correct architecture of your GPU card and it compiles k2 to support all possible architectures, which can take lots of time to compile.
> 
> thanks, I use the pytorch docker image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel to build a K2 dockerfile,the above warning occurs during building

Could you please run `nvidia-smi` and post the output here.

**Comment by cdxie** [comment]
> > > You can just ignore that warning.
> > > By the way, could you tell us the type/name of your nvidia GPU card? Looks like CMake didn't detect the correct architecture of your GPU card and it compiles k2 to support all possible architectures, which can take lots of time to compile.
> > 
> > 
> > thanks, I use the pytorch docker image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel to build a K2 dockerfile,the above warning occurs during building
> 
> Could you please run `nvidia-smi` and post the output here.

The  following is the output of `nvidia-smi`:

root@16798a06774e:/workspace# nvidia-smi
Mon Sep  6 14:30:23 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   30C    P0    35W / 250W |  10139MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   41C    P0    65W / 250W |   9089MiB / 16160MiB |     38%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by csukuangfj** [comment]
Your GPU is `Tesla V100`.

I would suggest you to replace
https://github.com/k2-fsa/k2/blob/818b138b33eabe440601df8910a2b97ac088594b/CMakeLists.txt#L206

with

```cmake
 set(K2_COMPUTE_ARCH_CANDIDATES 70) 
```

It accelerates compilation and reduces the size of the resulting library.

**Comment by cdxie** [comment]
> It accelerates compilation and reduces the size of the resulting library

OK，I try again 
Thank you very much
