### ISSUE TITLE
complie error: seems to have somethint to do with cuda

### ISSUE THREAD

**Issue by eggplant95** [k2-fsa/k2#909]
Hi, I am having trouble while try to complie k2 with CUDA, here is my cmd and erro log while i was doing it.
I am compiling on centos with cuda10.1 and cudnn 7.6.3.

`mkdir -p build && cd build && cmake -D CMAKE_CUDA_COMPILER="mypath/cuda10.1/bin/nvcc" -D CMAKE_CXX_COMPILER="mypath/gcc-7.5.0/gcc75/bin/g++" -D CUDNN_LIBRARY_PATH="mypath/cudnn/lib64/libcudnn.so" --CUDNN_INCLUDE_PATH="mypath/cudnn/include" -DCMAKE_BUILD_TYPE=Release ..`

> -- Enabled languages: CXX;CUDA
> -- The CXX compiler identification is GNU 7.5.0
> -- The CUDA compiler identification is NVIDIA 10.1.168
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: mypath/gcc-7.5.0/gcc75/bin/g++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting CUDA compiler ABI info
> -- Detecting CUDA compiler ABI info - done
> -- Check for working CUDA compiler: mypath/cuda10.1/bin/nvcc - skipped
> -- Detecting CUDA compile features
> -- Detecting CUDA compile features - done
> -- K2_OS: 
> -- Found Git: /usr/bin/git (found version "1.8.3.1") 
> -- Looking for C++ include cxxabi.h
> -- Looking for C++ include cxxabi.h - found
> -- Looking for C++ include execinfo.h
> -- Looking for C++ include execinfo.h - found
> -- Performing Test K2_COMPILER_SUPPORTS_CXX14
> -- Performing Test K2_COMPILER_SUPPORTS_CXX14 - Success
> -- C++ Standard version: 14
> -- Autodetected CUDA architecture(s):  7.0 7.0 7.0 7.0
> -- K2_COMPUTE_ARCH_FLAGS: -gencode;arch=compute_70,code=sm_70
> -- K2_COMPUTE_ARCH_CANDIDATES 35;50;60;61;70;75
> -- Skipping arch 35
> -- Skipping arch 50
> -- Skipping arch 60
> -- Skipping arch 61
> -- Adding arch 70
> -- Skipping arch 75
> -- K2_COMPUTE_ARCHS: 70
> -- Found Valgrind: /usr/bin  
> -- Found Valgrind: /usr/bin/valgrind
> -- To check memory, run `ctest -R <NAME> -D ExperimentalMemCheck`
> -- Downloading pybind11
> -- pybind11 is downloaded to mypath/k2/build/_deps/pybind11-src
> -- pybind11 v2.6.0 
> -- Found PythonInterp: mypath/anaconda3/bin/python (found version "3.7.1") 
> -- Found PythonLibs: mypath/anaconda3/lib/libpython3.7m.so
> -- Performing Test HAS_FLTO
> -- Performing Test HAS_FLTO - Success
> -- Python executable: mypath/anaconda3/bin/python
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found CUDA: mypath/cuda10.1 (found version "10.1") 
> -- Caffe2: CUDA detected: 10.1
> -- Caffe2: CUDA nvcc is: mypath/cuda10.1/bin/nvcc
> -- Caffe2: CUDA toolkit directory: mypath/cuda10.1
> -- Caffe2: Header version is: 10.1
> -- Found CUDNN: mypath/cudnn/lib64/libcudnn.so  
> -- Found cuDNN: v7.6.3  (include: mypath/cudnn/include, library:mypath/cudnn/lib64/libcudnn.so)
> -- /acoustic_data3/software/cuda10.1/lib64/libnvrtc.so shorthash is ed43b1d3
> -- Autodetected CUDA architecture(s):  7.0 7.0 7.0 7.0
> -- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70
> -- Found Torch: mypath/.local/lib/python3.7/site-packages/torch/lib/libtorch.so  
> -- PyTorch version: 1.8.1+cu101
> -- PyTorch cuda version: 10.1
> -- Downloading cub
> -- cub is downloaded to mypath/k2/build/_deps/cub-src
> -- Downloading moderngpu
> -- moderngpu is downloaded to mypath/k2/build/_deps/moderngpu-src
> -- Downloading googletest
> -- googletest is downloaded to mypath/k2/build/_deps/googletest-src
> -- googletest's binary dir ismypath/k2/build/_deps/googletest-build
> CMake Deprecation Warning at build/_deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- The C compiler identification is GNU 7.3.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /lustre_data/weidong/local/src/gcc-7.3.0-build/bin/gcc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> CMake Deprecation Warning at build/_deps/googletest-src/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> CMake Deprecation Warning at build/_deps/googletest-src/googletest/CMakeLists.txt:56 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- CMAKE_CUDA_FLAGS:  --expt-extended-lambda -gencode arch=compute_70,code=sm_70 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall --compiler-options -Wno-unknown-pragmas --compiler-options -Wno-strict-overflow
> -- CMAKE_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-strict-overflow
> -- Generated mypath/k2/build/k2/csrc/version.h
> -- PYTHON_LIBRARIES: mypathr/anaconda3/lib/libpython3.7m.so
> -- Configuring done
> -- Generating done
> -- Build files have been written to: mypath/k2/build

`make _k2`

this is the part where it went wrong

> Scanning dependencies of target k2_log
> [  0%] Building CUDA object k2/csrc/CMakeFiles/k2_log.dir/log.cu.o
> [  3%] Linking CUDA shared library ../../lib/libk2_log.so
> [  3%] Built target k2_log
> [  6%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/determinize.cc.o
> [  6%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/determinize_pruned.cc.o
> [  9%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa.cc.o
> [  9%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_equivalent.cc.o
> [ 12%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_renderer.cc.o
> [ 12%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_util.cc.o
> [ 15%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/intersect.cc.o
> [ 15%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/properties.cc.o
> [ 15%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/rmepsilon_pruned.cc.o
> [ 18%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/topsort.cc.o
> [ 18%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/util.cc.o
> [ 21%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/weights.cc.o
> [ 21%] Linking CXX shared library ../../../lib/libk2fsa.so
> [ 24%] Built target fsa
> Scanning dependencies of target context
> [ 27%] Building CUDA object k2/csrc/CMakeFiles/context.dir/algorithms.cu.o
> [ 27%] Building CUDA object k2/csrc/CMakeFiles/context.dir/array_ops.cu.o
> [ 30%] Building CUDA object k2/csrc/CMakeFiles/context.dir/connect.cu.o
> [ 30%] Building CUDA object k2/csrc/CMakeFiles/context.dir/context.cu.o
> [ 33%] Building CUDA object k2/csrc/CMakeFiles/context.dir/dtype.cu.o
> [ 33%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa.cu.o
> [ 36%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa_algo.cu.o
> [ 36%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa_utils.cu.o
> [ 39%] Building CUDA object k2/csrc/CMakeFiles/context.dir/hash.cu.o
> [ 39%] Building CUDA object k2/csrc/CMakeFiles/context.dir/host_shim.cu.o
> [ 42%] Building CUDA object k2/csrc/CMakeFiles/context.dir/intersect.cu.o
> [ 42%] Building CUDA object k2/csrc/CMakeFiles/context.dir/intersect_dense.cu.o
> [ 42%] Building CUDA object k2/csrc/CMakeFiles/context.dir/intersect_dense_pruned.cu.o
> [ 45%] Building CUDA object k2/csrc/CMakeFiles/context.dir/math.cu.o
> [ 45%] Building CUDA object k2/csrc/CMakeFiles/context.dir/moderngpu_allocator.cu.o
> [ 48%] Building CUDA object k2/csrc/CMakeFiles/context.dir/pinned_context.cu.o
> [ 48%] Building CUDA object k2/csrc/CMakeFiles/context.dir/ragged.cu.o
> [ 51%] Building CUDA object k2/csrc/CMakeFiles/context.dir/ragged_ops.cu.o
> [ 51%] Building CUDA object k2/csrc/CMakeFiles/context.dir/ragged_utils.cu.o
> [ 54%] Building CUDA object k2/csrc/CMakeFiles/context.dir/rand.cu.o
> [ 54%] Building CUDA object k2/csrc/CMakeFiles/context.dir/rm_epsilon.cu.o
> [ 57%] Building CUDA object k2/csrc/CMakeFiles/context.dir/tensor.cu.o
> [ 57%] Building CUDA object k2/csrc/CMakeFiles/context.dir/tensor_ops.cu.o
> [ 60%] Building CUDA object k2/csrc/CMakeFiles/context.dir/thread_pool.cu.o
> [ 60%] Building CUDA object k2/csrc/CMakeFiles/context.dir/timer.cu.o
> [ 63%] Building CUDA object k2/csrc/CMakeFiles/context.dir/top_sort.cu.o
> [ 63%] Building CUDA object k2/csrc/CMakeFiles/context.dir/utils.cu.o
> [ 66%] Building CUDA object k2/csrc/CMakeFiles/context.dir/nbest.cu.o
> mypath/k2/k2/csrc/nbest.cu: In instantiation of ‘void k2::CreateSuffixArray(const T*, T, T, T*) [with T = int]’:
> mypath/k2/k2/csrc/nbest.cu:136:89:   required from here
> mypath/k2/csrc/nbest.cu:74:9: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
>    T *R0 = new T[n0];
>          ^~~~~~~~~~~~
> mypath/k2/csrc/nbest.cu:75:10: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
>    T *SA0 = new T[n0];
>           ^~~~~~~~~~~~
> mypath/csrc/nbest.cu: In instantiation of ‘void k2::CreateSuffixArray(const T*, T, T, T*) [with T = short int]’:
> mypath/k2/k2/k2/csrc/nbest.cu:138:89:   required from here
> mypath/k2/k2/k2/csrc/nbest.cu:74:9: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
>    T *R0 = new T[n0];
>          ^~~~~~~~~~~~
> mypath/k2/k2/k2/csrc/nbest.cu:75:10: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
>    T *SA0 = new T[n0];
>           ^~~~~~~~~~~~
> [ 66%] Building CUDA object k2/csrc/CMakeFiles/context.dir/pytorch_context.cu.o
> [ 69%] Building CUDA object k2/csrc/CMakeFiles/context.dir/cudpp/cudpp.cu.o
> [ 69%] Linking CUDA device code CMakeFiles/context.dir/cmake_device_link.o
> nvlink error   : Entry function '_ZN2k23cub28DeviceRadixSortUpsweepKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0ELb0EiiEEvPKT2_PT3_S8_iiNS0_13GridEvenShareIS8_EE' uses too much shared data (0xd810 bytes, 0xc000 max) (target: sm_70)
> nvlink error   : Entry function '_ZN2k23cub30DeviceRadixSortDownsweepKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb1ELb0EiiiEEvPKT2_PS5_PKT3_PS9_PT4_SD_iiNS0_13GridEvenShareISD_EE' uses too much shared data (0x11510 bytes, 0xc000 max) (target: sm_70)
> nvlink error   : Entry function '_ZN2k23cub23RadixSortScanBinsKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800EiEEvPT0_i' uses too much shared data (0x11020 bytes, 0xc000 max) (target: sm_70)
> nvlink error   : Entry function '_ZN2k23cub30DeviceRadixSortDownsweepKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0ELb0EiiiEEvPKT2_PS5_PKT3_PS9_PT4_SD_iiNS0_13GridEvenShareISD_EE' uses too much shared data (0x11210 bytes, 0xc000 max) (target: sm_70)
> nvlink error   : Entry function '_ZN2k23cub29DeviceRadixSortOnesweepKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0EiiiiEEvPT4_S6_PT3_PKS7_PT1_PKSB_PT2_PKSF_S7_ii' uses too much shared data (0x11410 bytes, 0xc000 max) (target: sm_70)
> nvlink error   : Entry function '_ZN2k23cub31DeviceRadixSortSingleTileKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0EiiiEEvPKT1_PS5_PKT2_PS9_T3_ii' uses too much shared data (0xdc50 bytes, 0xc000 max) (target: sm_70)
> nvlink error   : Entry function '_ZN2k23cub30DeviceRadixSortHistogramKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0EiiEEvPT2_PKT1_S5_ii' uses too much shared data (0xd810 bytes, 0xc000 max) (target: sm_70)
> make[3]: *** [k2/csrc/CMakeFiles/context.dir/cmake_device_link.o] Error 255
> make[2]: *** [k2/csrc/CMakeFiles/context.dir/all] Error 2
> make[1]: *** [k2/python/csrc/CMakeFiles/_k2.dir/rule] Error 2
> make: *** [_k2] Error 2

**Comment by csukuangfj** [comment]
There are some CMake warnings. I am not sure whether the error is related to your CMake version.
Can you try CMake 3.11 or 3.18?

**Comment by eggplant95** [comment]
I have tried 3.11 and 3.18 ,but the results remains the same. 

while checking the CMakeError.log.

> /usr/bin/ld: cannot find -lpthreads
> collect2: error: ld returned 1 exit status
> gmake[1]: *** [cmTC_c7df3] Error 1
> gmake[1]: Leaving directory `mypath/k2/build/CMakeFiles/CMakeTmp'
> gmake: *** [cmTC_c7df3/fast] Error 2

**Comment by csukuangfj** [comment]
> while checking the CMakeError.log.
> /usr/bin/ld: cannot find -lpthreads

I also have such kinds of error logs locally. They are produced by CMake while checking the existence of `pthread` and should not affect your building.

---

The error that is causing the failure is:

> nvlink error : Entry function '_ZN2k23cub23RadixSortScanBinsKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800EiEEvPT0_i' uses too much shared data (0x11020 bytes, 0xc000 max) (target: sm_70)

But I am using the same `sm_70` as yours and it works fine.  I only find that you are using centos while I am using Ubuntu.
Not sure what is the problem.

**Comment by csukuangfj** [comment]
> -- The CUDA compiler identification is NVIDIA 10.1.168

Also, I am not sure whether it is caused by your version of NVCC. There are several updates of CUDA 10.1 at https://developer.nvidia.com/cuda-toolkit-archive
<img width="522" alt="Screen Shot 2022-01-29 at 4 02 58 PM" src="https://user-images.githubusercontent.com/5284924/151653081-4f2fe3eb-6710-4775-8993-cfca530ba912.png">

Could you try `update 2`, which can be downloaded from https://developer.nvidia.com/cuda-10.1-download-archive-update2

**Comment by leofbank** [comment]
met the same problem, any 


> Hi, I am having trouble while try to complie k2 with CUDA, here is my cmd and erro log while i was doing it. I am compiling on centos with cuda10.1 and cudnn 7.6.3.
> 
> `mkdir -p build && cd build && cmake -D CMAKE_CUDA_COMPILER="mypath/cuda10.1/bin/nvcc" -D CMAKE_CXX_COMPILER="mypath/gcc-7.5.0/gcc75/bin/g++" -D CUDNN_LIBRARY_PATH="mypath/cudnn/lib64/libcudnn.so" --CUDNN_INCLUDE_PATH="mypath/cudnn/include" -DCMAKE_BUILD_TYPE=Release ..`
> 
> > -- Enabled languages: CXX;CUDA
> > -- The CXX compiler identification is GNU 7.5.0
> > -- The CUDA compiler identification is NVIDIA 10.1.168
> > -- Detecting CXX compiler ABI info
> > -- Detecting CXX compiler ABI info - done
> > -- Check for working CXX compiler: mypath/gcc-7.5.0/gcc75/bin/g++ - skipped
> > -- Detecting CXX compile features
> > -- Detecting CXX compile features - done
> > -- Detecting CUDA compiler ABI info
> > -- Detecting CUDA compiler ABI info - done
> > -- Check for working CUDA compiler: mypath/cuda10.1/bin/nvcc - skipped
> > -- Detecting CUDA compile features
> > -- Detecting CUDA compile features - done
> > -- K2_OS:
> > -- Found Git: /usr/bin/git (found version "1.8.3.1")
> > -- Looking for C++ include cxxabi.h
> > -- Looking for C++ include cxxabi.h - found
> > -- Looking for C++ include execinfo.h
> > -- Looking for C++ include execinfo.h - found
> > -- Performing Test K2_COMPILER_SUPPORTS_CXX14
> > -- Performing Test K2_COMPILER_SUPPORTS_CXX14 - Success
> > -- C++ Standard version: 14
> > -- Autodetected CUDA architecture(s):  7.0 7.0 7.0 7.0
> > -- K2_COMPUTE_ARCH_FLAGS: -gencode;arch=compute_70,code=sm_70
> > -- K2_COMPUTE_ARCH_CANDIDATES 35;50;60;61;70;75
> > -- Skipping arch 35
> > -- Skipping arch 50
> > -- Skipping arch 60
> > -- Skipping arch 61
> > -- Adding arch 70
> > -- Skipping arch 75
> > -- K2_COMPUTE_ARCHS: 70
> > -- Found Valgrind: /usr/bin
> > -- Found Valgrind: /usr/bin/valgrind
> > -- To check memory, run `ctest -R <NAME> -D ExperimentalMemCheck`
> > -- Downloading pybind11
> > -- pybind11 is downloaded to mypath/k2/build/_deps/pybind11-src
> > -- pybind11 v2.6.0
> > -- Found PythonInterp: mypath/anaconda3/bin/python (found version "3.7.1")
> > -- Found PythonLibs: mypath/anaconda3/lib/libpython3.7m.so
> > -- Performing Test HAS_FLTO
> > -- Performing Test HAS_FLTO - Success
> > -- Python executable: mypath/anaconda3/bin/python
> > -- Looking for C++ include pthread.h
> > -- Looking for C++ include pthread.h - found
> > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> > -- Looking for pthread_create in pthreads
> > -- Looking for pthread_create in pthreads - not found
> > -- Looking for pthread_create in pthread
> > -- Looking for pthread_create in pthread - found
> > -- Found Threads: TRUE
> > -- Found CUDA: mypath/cuda10.1 (found version "10.1")
> > -- Caffe2: CUDA detected: 10.1
> > -- Caffe2: CUDA nvcc is: mypath/cuda10.1/bin/nvcc
> > -- Caffe2: CUDA toolkit directory: mypath/cuda10.1
> > -- Caffe2: Header version is: 10.1
> > -- Found CUDNN: mypath/cudnn/lib64/libcudnn.so
> > -- Found cuDNN: v7.6.3  (include: mypath/cudnn/include, library:mypath/cudnn/lib64/libcudnn.so)
> > -- /acoustic_data3/software/cuda10.1/lib64/libnvrtc.so shorthash is ed43b1d3
> > -- Autodetected CUDA architecture(s):  7.0 7.0 7.0 7.0
> > -- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70
> > -- Found Torch: mypath/.local/lib/python3.7/site-packages/torch/lib/libtorch.so
> > -- PyTorch version: 1.8.1+cu101
> > -- PyTorch cuda version: 10.1
> > -- Downloading cub
> > -- cub is downloaded to mypath/k2/build/_deps/cub-src
> > -- Downloading moderngpu
> > -- moderngpu is downloaded to mypath/k2/build/_deps/moderngpu-src
> > -- Downloading googletest
> > -- googletest is downloaded to mypath/k2/build/_deps/googletest-src
> > -- googletest's binary dir ismypath/k2/build/_deps/googletest-build
> > CMake Deprecation Warning at build/_deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
> > Compatibility with CMake < 2.8.12 will be removed from a future version of
> > CMake.
> > Update the VERSION argument  value or use a ... suffix to tell
> > CMake that the project does not need compatibility with older versions.
> > -- The C compiler identification is GNU 7.3.0
> > -- Detecting C compiler ABI info
> > -- Detecting C compiler ABI info - done
> > -- Check for working C compiler: /lustre_data/weidong/local/src/gcc-7.3.0-build/bin/gcc - skipped
> > -- Detecting C compile features
> > -- Detecting C compile features - done
> > CMake Deprecation Warning at build/_deps/googletest-src/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
> > Compatibility with CMake < 2.8.12 will be removed from a future version of
> > CMake.
> > Update the VERSION argument  value or use a ... suffix to tell
> > CMake that the project does not need compatibility with older versions.
> > CMake Deprecation Warning at build/_deps/googletest-src/googletest/CMakeLists.txt:56 (cmake_minimum_required):
> > Compatibility with CMake < 2.8.12 will be removed from a future version of
> > CMake.
> > Update the VERSION argument  value or use a ... suffix to tell
> > CMake that the project does not need compatibility with older versions.
> > -- CMAKE_CUDA_FLAGS:  --expt-extended-lambda -gencode arch=compute_70,code=sm_70 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall --compiler-options -Wno-unknown-pragmas --compiler-options -Wno-strict-overflow
> > -- CMAKE_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=0 -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-strict-overflow
> > -- Generated mypath/k2/build/k2/csrc/version.h
> > -- PYTHON_LIBRARIES: mypathr/anaconda3/lib/libpython3.7m.so
> > -- Configuring done
> > -- Generating done
> > -- Build files have been written to: mypath/k2/build
> 
> `make _k2`
> 
> this is the part where it went wrong
> 
> > Scanning dependencies of target k2_log
> > [  0%] Building CUDA object k2/csrc/CMakeFiles/k2_log.dir/log.cu.o
> > [  3%] Linking CUDA shared library ../../lib/libk2_log.so
> > [  3%] Built target k2_log
> > [  6%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/determinize.cc.o
> > [  6%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/determinize_pruned.cc.o
> > [  9%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa.cc.o
> > [  9%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_equivalent.cc.o
> > [ 12%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_renderer.cc.o
> > [ 12%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/fsa_util.cc.o
> > [ 15%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/intersect.cc.o
> > [ 15%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/properties.cc.o
> > [ 15%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/rmepsilon_pruned.cc.o
> > [ 18%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/topsort.cc.o
> > [ 18%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/util.cc.o
> > [ 21%] Building CXX object k2/csrc/host/CMakeFiles/fsa.dir/weights.cc.o
> > [ 21%] Linking CXX shared library ../../../lib/libk2fsa.so
> > [ 24%] Built target fsa
> > Scanning dependencies of target context
> > [ 27%] Building CUDA object k2/csrc/CMakeFiles/context.dir/algorithms.cu.o
> > [ 27%] Building CUDA object k2/csrc/CMakeFiles/context.dir/array_ops.cu.o
> > [ 30%] Building CUDA object k2/csrc/CMakeFiles/context.dir/connect.cu.o
> > [ 30%] Building CUDA object k2/csrc/CMakeFiles/context.dir/context.cu.o
> > [ 33%] Building CUDA object k2/csrc/CMakeFiles/context.dir/dtype.cu.o
> > [ 33%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa.cu.o
> > [ 36%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa_algo.cu.o
> > [ 36%] Building CUDA object k2/csrc/CMakeFiles/context.dir/fsa_utils.cu.o
> > [ 39%] Building CUDA object k2/csrc/CMakeFiles/context.dir/hash.cu.o
> > [ 39%] Building CUDA object k2/csrc/CMakeFiles/context.dir/host_shim.cu.o
> > [ 42%] Building CUDA object k2/csrc/CMakeFiles/context.dir/intersect.cu.o
> > [ 42%] Building CUDA object k2/csrc/CMakeFiles/context.dir/intersect_dense.cu.o
> > [ 42%] Building CUDA object k2/csrc/CMakeFiles/context.dir/intersect_dense_pruned.cu.o
> > [ 45%] Building CUDA object k2/csrc/CMakeFiles/context.dir/math.cu.o
> > [ 45%] Building CUDA object k2/csrc/CMakeFiles/context.dir/moderngpu_allocator.cu.o
> > [ 48%] Building CUDA object k2/csrc/CMakeFiles/context.dir/pinned_context.cu.o
> > [ 48%] Building CUDA object k2/csrc/CMakeFiles/context.dir/ragged.cu.o
> > [ 51%] Building CUDA object k2/csrc/CMakeFiles/context.dir/ragged_ops.cu.o
> > [ 51%] Building CUDA object k2/csrc/CMakeFiles/context.dir/ragged_utils.cu.o
> > [ 54%] Building CUDA object k2/csrc/CMakeFiles/context.dir/rand.cu.o
> > [ 54%] Building CUDA object k2/csrc/CMakeFiles/context.dir/rm_epsilon.cu.o
> > [ 57%] Building CUDA object k2/csrc/CMakeFiles/context.dir/tensor.cu.o
> > [ 57%] Building CUDA object k2/csrc/CMakeFiles/context.dir/tensor_ops.cu.o
> > [ 60%] Building CUDA object k2/csrc/CMakeFiles/context.dir/thread_pool.cu.o
> > [ 60%] Building CUDA object k2/csrc/CMakeFiles/context.dir/timer.cu.o
> > [ 63%] Building CUDA object k2/csrc/CMakeFiles/context.dir/top_sort.cu.o
> > [ 63%] Building CUDA object k2/csrc/CMakeFiles/context.dir/utils.cu.o
> > [ 66%] Building CUDA object k2/csrc/CMakeFiles/context.dir/nbest.cu.o
> > mypath/k2/k2/csrc/nbest.cu: In instantiation of ‘void k2::CreateSuffixArray(const T*, T, T, T*) [with T = int]’:
> > mypath/k2/k2/csrc/nbest.cu:136:89:   required from here
> > mypath/k2/csrc/nbest.cu:74:9: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
> > T _R0 = new T[n0];
> > ^~~~~~~~~~~~
> > mypath/k2/csrc/nbest.cu:75:10: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
> > T _SA0 = new T[n0];
> > ^~~~~~~~~~~~
> > mypath/csrc/nbest.cu: In instantiation of ‘void k2::CreateSuffixArray(const T_, T, T, T_) [with T = short int]’:
> > mypath/k2/k2/k2/csrc/nbest.cu:138:89:   required from here
> > mypath/k2/k2/k2/csrc/nbest.cu:74:9: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
> > T *R0 = new T[n0];
> > ^~~~~~~~~~~~
> > mypath/k2/k2/k2/csrc/nbest.cu:75:10: warning: non-constant array new length must be specified without parentheses around the type-id [-Wvla]
> > T *SA0 = new T[n0];
> > ^~~~~~~~~~~~
> > [ 66%] Building CUDA object k2/csrc/CMakeFiles/context.dir/pytorch_context.cu.o
> > [ 69%] Building CUDA object k2/csrc/CMakeFiles/context.dir/cudpp/cudpp.cu.o
> > [ 69%] Linking CUDA device code CMakeFiles/context.dir/cmake_device_link.o
> > nvlink error   : Entry function '_ZN2k23cub28DeviceRadixSortUpsweepKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0ELb0EiiEEvPKT2_PT3_S8_iiNS0_13GridEvenShareIS8_EE' uses too much shared data (0xd810 bytes, 0xc000 max) (target: sm_70)
> > nvlink error   : Entry function '_ZN2k23cub30DeviceRadixSortDownsweepKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb1ELb0EiiiEEvPKT2_PS5_PKT3_PS9_PT4_SD_iiNS0_13GridEvenShareISD_EE' uses too much shared data (0x11510 bytes, 0xc000 max) (target: sm_70)
> > nvlink error   : Entry function '_ZN2k23cub23RadixSortScanBinsKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800EiEEvPT0_i' uses too much shared data (0x11020 bytes, 0xc000 max) (target: sm_70)
> > nvlink error   : Entry function '_ZN2k23cub30DeviceRadixSortDownsweepKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0ELb0EiiiEEvPKT2_PS5_PKT3_PS9_PT4_SD_iiNS0_13GridEvenShareISD_EE' uses too much shared data (0x11210 bytes, 0xc000 max) (target: sm_70)
> > nvlink error   : Entry function '_ZN2k23cub29DeviceRadixSortOnesweepKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0EiiiiEEvPT4_S6_PT3_PKS7_PT1_PKSB_PT2_PKSF_S7_ii' uses too much shared data (0x11410 bytes, 0xc000 max) (target: sm_70)
> > nvlink error   : Entry function '_ZN2k23cub31DeviceRadixSortSingleTileKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0EiiiEEvPKT1_PS5_PKT2_PS9_T3_ii' uses too much shared data (0xdc50 bytes, 0xc000 max) (target: sm_70)
> > nvlink error   : Entry function '_ZN2k23cub30DeviceRadixSortHistogramKernelINS0_21DeviceRadixSortPolicyIiiiE9Policy800ELb0EiiEEvPT2_PKT1_S5_ii' uses too much shared data (0xd810 bytes, 0xc000 max) (target: sm_70)
> > make[3]: *** [k2/csrc/CMakeFiles/context.dir/cmake_device_link.o] Error 255
> > make[2]: *** [k2/csrc/CMakeFiles/context.dir/all] Error 2
> > make[1]: *** [k2/python/csrc/CMakeFiles/_k2.dir/rule] Error 2
> > make: *** [_k2] Error 2

Met the same problem, have you managed to solve this problem?

**Comment by csukuangfj** [comment]
> Met the same problem, have you managed to solve this problem?

Have you tried the suggestions in https://github.com/k2-fsa/k2/issues/909#issuecomment-1024861681 ?

**Comment by leofbank** [comment]
> > Met the same problem, have you managed to solve this problem?
> 
> Have you tried the suggestions in [#909 (comment)](https://github.com/k2-fsa/k2/issues/909#issuecomment-1024861681) ?

I have not. I will give it a try and let you know.

**Comment by leofbank** [comment]
> > Met the same problem, have you managed to solve this problem?
> 
> Have you tried the suggestions in [#909 (comment)](https://github.com/k2-fsa/k2/issues/909#issuecomment-1024861681) ?

After update NVIDIA 10.1.168 to NVIDIA 10.1.243(CUDA10.1 update2), the problem is solved.  : )

**Comment by eggplant95** [comment]
> > > Met the same problem, have you managed to solve this problem?
> > 
> > 
> > Have you tried the suggestions in [#909 (comment)](https://github.com/k2-fsa/k2/issues/909#issuecomment-1024861681) ?
> 
> After update NVIDIA 10.1.168 to NVIDIA 10.1.243(CUDA10.1 update2), the problem is solved. : )

Me too. Thank you for your support @csukuangfj
